spring:
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.sehoon.platform: DEBUG
    org.springframework.security: INFO
