server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: when-authorized

app:
  todo:
    base-url: ${TODO_API_URL}
  auth:
    platform-url: ${PLATFORM_URL}
